simulator: heap.o keyeditem.o priorityqueue.o simulator.o main.o
	g++ heap.o keyeditem.o priorityqueue.o simulator.o main.o -o simulator

heap.o: heap.cpp
	g++ -c heap.cpp

keyeditem.o: keyeditem.cpp
	g++ -c keyeditem.cpp

priorityqueue.o: priorityqueue.cpp
	g++ -c priorityqueue.cpp

simulator.o: simulator.cpp
	g++ -c simulator.cpp

main.o: main.cpp
	g++ -c main.cpp